import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'nl' | 'en' | 'es' | 'de' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  nl: {
    home: 'Home',
    products: 'Producten',
    contact: 'Contact',
    login: 'Inloggen',
    register: 'Registreren',
    logout: 'Uitloggen',
    myAccount: 'Mijn Account',
    cart: 'Winkelmand',
    wishlist: 'Favorieten',
    search: 'Zoeken',
    shopNow: 'Shop Nu',
    addToCart: 'Toevoegen aan Winkelmand',
    addToWishlist: 'Toevoegen aan Favorieten',
    price: 'Prijs',
    size: 'Formaat',
    popularity: 'Populariteit',
    inStock: 'Op voorraad',
    outOfStock: 'Uitverkocht',
    featuredProducts: 'Uitgelichte Producten',
    allProducts: 'Alle Producten',
    productDetails: 'Productdetails',
    quantity: 'Aantal',
    subtotal: 'Subtotaal',
    vat: 'BTW',
    shipping: 'Verzendkosten',
    total: 'Totaal',
    checkout: 'Afrekenen',
    shippingAddress: 'Verzendadres',
    billingAddress: 'Factuuradres',
    payment: 'Betaling',
    placeOrder: 'Bestelling Plaatsen',
    orderConfirmation: 'Bestelbevestiging',
    myOrders: 'Mijn Bestellingen',
    orderStatus: 'Bestelstatus',
    processing: 'In behandeling',
    shipped: 'Verzonden',
    delivered: 'Geleverd',
    profile: 'Profiel',
    settings: 'Instellingen',
    faq: 'FAQ',
    terms: 'Algemene Voorwaarden',
    returns: 'Retourbeleid',
    admin: 'Beheer',
    manageProducts: 'Producten Beheren',
    manageOrders: 'Bestellingen Beheren',
    email: 'E-mail',
    password: 'Wachtwoord',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    address: 'Adres',
    city: 'Stad',
    postalCode: 'Postcode',
    country: 'Land',
    phone: 'Telefoonnummer',
    filterBy: 'Filteren op',
    sortBy: 'Sorteren op',
    remove: 'Verwijderen',
    edit: 'Bewerken',
    save: 'Opslaan',
    cancel: 'Annuleren',
    previous: 'Vorige',
    next: 'Volgende',
  },
  en: {
    home: 'Home',
    products: 'Products',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    myAccount: 'My Account',
    cart: 'Cart',
    wishlist: 'Wishlist',
    search: 'Search',
    shopNow: 'Shop Now',
    addToCart: 'Add to Cart',
    addToWishlist: 'Add to Wishlist',
    price: 'Price',
    size: 'Size',
    popularity: 'Popularity',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    featuredProducts: 'Featured Products',
    allProducts: 'All Products',
    productDetails: 'Product Details',
    quantity: 'Quantity',
    subtotal: 'Subtotal',
    vat: 'VAT',
    shipping: 'Shipping',
    total: 'Total',
    checkout: 'Checkout',
    shippingAddress: 'Shipping Address',
    billingAddress: 'Billing Address',
    payment: 'Payment',
    placeOrder: 'Place Order',
    orderConfirmation: 'Order Confirmation',
    myOrders: 'My Orders',
    orderStatus: 'Order Status',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    profile: 'Profile',
    settings: 'Settings',
    faq: 'FAQ',
    terms: 'Terms & Conditions',
    returns: 'Returns Policy',
    admin: 'Admin',
    manageProducts: 'Manage Products',
    manageOrders: 'Manage Orders',
    email: 'Email',
    password: 'Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    address: 'Address',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    phone: 'Phone',
    filterBy: 'Filter by',
    sortBy: 'Sort by',
    remove: 'Remove',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    previous: 'Previous',
    next: 'Next',
  },
  es: {
    home: 'Inicio',
    products: 'Productos',
    contact: 'Contacto',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    myAccount: 'Mi Cuenta',
    cart: 'Carrito',
    wishlist: 'Favoritos',
    search: 'Buscar',
    shopNow: 'Comprar Ahora',
    addToCart: 'Añadir al Carrito',
    addToWishlist: 'Añadir a Favoritos',
    price: 'Precio',
    size: 'Tamaño',
    popularity: 'Popularidad',
    inStock: 'En Stock',
    outOfStock: 'Agotado',
    featuredProducts: 'Productos Destacados',
    allProducts: 'Todos los Productos',
    productDetails: 'Detalles del Producto',
    quantity: 'Cantidad',
    subtotal: 'Subtotal',
    vat: 'IVA',
    shipping: 'Envío',
    total: 'Total',
    checkout: 'Finalizar Compra',
    shippingAddress: 'Dirección de Envío',
    billingAddress: 'Dirección de Facturación',
    payment: 'Pago',
    placeOrder: 'Realizar Pedido',
    orderConfirmation: 'Confirmación de Pedido',
    myOrders: 'Mis Pedidos',
    orderStatus: 'Estado del Pedido',
    processing: 'En Proceso',
    shipped: 'Enviado',
    delivered: 'Entregado',
    profile: 'Perfil',
    settings: 'Configuración',
    faq: 'Preguntas Frecuentes',
    terms: 'Términos y Condiciones',
    returns: 'Política de Devoluciones',
    admin: 'Administración',
    manageProducts: 'Gestionar Productos',
    manageOrders: 'Gestionar Pedidos',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    firstName: 'Nombre',
    lastName: 'Apellido',
    address: 'Dirección',
    city: 'Ciudad',
    postalCode: 'Código Postal',
    country: 'País',
    phone: 'Teléfono',
    filterBy: 'Filtrar por',
    sortBy: 'Ordenar por',
    remove: 'Eliminar',
    edit: 'Editar',
    save: 'Guardar',
    cancel: 'Cancelar',
    previous: 'Anterior',
    next: 'Siguiente',
  },
  de: {
    home: 'Startseite',
    products: 'Produkte',
    contact: 'Kontakt',
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    myAccount: 'Mein Konto',
    cart: 'Warenkorb',
    wishlist: 'Wunschliste',
    search: 'Suchen',
    shopNow: 'Jetzt Einkaufen',
    addToCart: 'In den Warenkorb',
    addToWishlist: 'Zur Wunschliste',
    price: 'Preis',
    size: 'Größe',
    popularity: 'Beliebtheit',
    inStock: 'Auf Lager',
    outOfStock: 'Ausverkauft',
    featuredProducts: 'Ausgewählte Produkte',
    allProducts: 'Alle Produkte',
    productDetails: 'Produktdetails',
    quantity: 'Menge',
    subtotal: 'Zwischensumme',
    vat: 'MwSt',
    shipping: 'Versand',
    total: 'Gesamt',
    checkout: 'Zur Kasse',
    shippingAddress: 'Lieferadresse',
    billingAddress: 'Rechnungsadresse',
    payment: 'Zahlung',
    placeOrder: 'Bestellung Aufgeben',
    orderConfirmation: 'Bestellbestätigung',
    myOrders: 'Meine Bestellungen',
    orderStatus: 'Bestellstatus',
    processing: 'In Bearbeitung',
    shipped: 'Versandt',
    delivered: 'Geliefert',
    profile: 'Profil',
    settings: 'Einstellungen',
    faq: 'Häufig gestellte Fragen',
    terms: 'Geschäftsbedingungen',
    returns: 'Rückgaberecht',
    admin: 'Verwaltung',
    manageProducts: 'Produkte Verwalten',
    manageOrders: 'Bestellungen Verwalten',
    email: 'E-Mail',
    password: 'Passwort',
    firstName: 'Vorname',
    lastName: 'Nachname',
    address: 'Adresse',
    city: 'Stadt',
    postalCode: 'Postleitzahl',
    country: 'Land',
    phone: 'Telefon',
    filterBy: 'Filtern nach',
    sortBy: 'Sortieren nach',
    remove: 'Entfernen',
    edit: 'Bearbeiten',
    save: 'Speichern',
    cancel: 'Abbrechen',
    previous: 'Zurück',
    next: 'Weiter',
  },
  ru: {
    home: 'Главная',
    products: 'Товары',
    contact: 'Контакты',
    login: 'Войти',
    register: 'Регистрация',
    logout: 'Выйти',
    myAccount: 'Мой Аккаунт',
    cart: 'Корзина',
    wishlist: 'Избранное',
    search: 'Поиск',
    shopNow: 'Купить Сейчас',
    addToCart: 'Добавить в Корзину',
    addToWishlist: 'Добавить в Избранное',
    price: 'Цена',
    size: 'Размер',
    popularity: 'Популярность',
    inStock: 'В наличии',
    outOfStock: 'Нет в наличии',
    featuredProducts: 'Рекомендуемые Товары',
    allProducts: 'Все Товары',
    productDetails: 'Детали Товара',
    quantity: 'Количество',
    subtotal: 'Промежуточный итог',
    vat: 'НДС',
    shipping: 'Доставка',
    total: 'Итого',
    checkout: 'Оформить Заказ',
    shippingAddress: 'Адрес Доставки',
    billingAddress: 'Адрес для Счета',
    payment: 'Оплата',
    placeOrder: 'Разместить Заказ',
    orderConfirmation: 'Подтверждение Заказа',
    myOrders: 'Мои Заказы',
    orderStatus: 'Статус Заказа',
    processing: 'Обрабатывается',
    shipped: 'Отправлен',
    delivered: 'Доставлен',
    profile: 'Профиль',
    settings: 'Настройки',
    faq: 'Часто Задаваемые Вопросы',
    terms: 'Условия и Положения',
    returns: 'Политика Возврата',
    admin: 'Администрирование',
    manageProducts: 'Управление Товарами',
    manageOrders: 'Управление Заказами',
    email: 'Электронная Почта',
    password: 'Пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    address: 'Адрес',
    city: 'Город',
    postalCode: 'Почтовый Индекс',
    country: 'Страна',
    phone: 'Телефон',
    filterBy: 'Фильтровать по',
    sortBy: 'Сортировать по',
    remove: 'Удалить',
    edit: 'Редактировать',
    save: 'Сохранить',
    cancel: 'Отмена',
    previous: 'Предыдущий',
    next: 'Следующий',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('nl'); // Default language is Dutch

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}